-- Mi plata: dónde está el dinero (caja, casa, Nequi). Todo tabla nueva: no toca ventas, gastos ni pedidos.

-- Plata que entra y no es una venta del sistema (ej. cobro de una deuda)
CREATE TABLE ingreso (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_uid  VARCHAR(64)  NOT NULL,
    concepto    VARCHAR(120),
    monto       BIGINT       NOT NULL,
    lugar       VARCHAR(10)  NOT NULL,
    creado_en   TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_ingreso_client_uid UNIQUE (client_uid),
    CONSTRAINT ck_ingreso_monto CHECK (monto > 0),
    CONSTRAINT ck_ingreso_lugar CHECK (lugar IN ('CAJA', 'CASA', 'NEQUI'))
);
CREATE INDEX ix_ingreso_creado_en ON ingreso (creado_en);

-- Cada vez que cuentas tu plata queda un conteo; el saldo sale del último más lo que se movió después
CREATE TABLE conteo_plata (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_uid  VARCHAR(64)  NOT NULL,
    caja        BIGINT       NOT NULL,
    casa        BIGINT       NOT NULL,
    nequi       BIGINT       NOT NULL,
    creado_en   TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_conteo_plata_client_uid UNIQUE (client_uid),
    CONSTRAINT ck_conteo_plata CHECK (caja >= 0 AND casa >= 0 AND nequi >= 0)
);
CREATE INDEX ix_conteo_plata_creado_en ON conteo_plata (creado_en);

-- Lo que se le pagó a Energy Cocktails al recibir un pedido (uno por pedido)
CREATE TABLE pago_proveedor (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id   BIGINT       NOT NULL,
    monto       BIGINT       NOT NULL,
    lugar       VARCHAR(10)  NOT NULL,
    creado_en   TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_pago_proveedor_pedido UNIQUE (pedido_id),
    CONSTRAINT ck_pago_proveedor_monto CHECK (monto > 0),
    CONSTRAINT ck_pago_proveedor_lugar CHECK (lugar IN ('CAJA', 'CASA', 'NEQUI'))
);
CREATE INDEX ix_pago_proveedor_creado_en ON pago_proveedor (creado_en);
