-- Mover plata entre lugares (caja, casa, Nequi) sin recontar todo
CREATE TABLE traslado (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_uid  VARCHAR(64)  NOT NULL,
    monto       BIGINT       NOT NULL,
    desde       VARCHAR(10)  NOT NULL,
    hacia       VARCHAR(10)  NOT NULL,
    creado_en   TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_traslado_client_uid UNIQUE (client_uid),
    CONSTRAINT ck_traslado_monto CHECK (monto > 0),
    CONSTRAINT ck_traslado_desde CHECK (desde IN ('CAJA', 'CASA', 'NEQUI')),
    CONSTRAINT ck_traslado_hacia CHECK (hacia IN ('CAJA', 'CASA', 'NEQUI')),
    CONSTRAINT ck_traslado_distintos CHECK (desde <> hacia)
);
CREATE INDEX ix_traslado_creado_en ON traslado (creado_en);

-- Un ingreso puede ser ganancia (cobro de una venta vieja) o solo plata tuya (un aporte).
-- Los que ya existen quedan como ganancia: hasta hoy eran cobros de ventas.
ALTER TABLE ingreso ADD COLUMN cuenta_ganancia BOOLEAN NOT NULL DEFAULT TRUE;

-- Metas ("sobres"): plata apartada para algo (el pedido, ahorro, una moto...). Sigue siendo tuya, pero no es plata libre.
CREATE TABLE meta_plata (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_uid  VARCHAR(64)  NOT NULL,
    nombre      VARCHAR(40)  NOT NULL,
    objetivo    BIGINT       NOT NULL DEFAULT 0,
    creado_en   TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_meta_plata_client_uid UNIQUE (client_uid),
    CONSTRAINT ck_meta_plata_objetivo CHECK (objetivo >= 0)
);

-- Cada vez que apartas (+) o sacas (−) plata de una meta
CREATE TABLE aporte_meta (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_uid  VARCHAR(64)  NOT NULL,
    meta_id     BIGINT       NOT NULL REFERENCES meta_plata (id),
    monto       BIGINT       NOT NULL,
    creado_en   TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_aporte_meta_client_uid UNIQUE (client_uid),
    CONSTRAINT ck_aporte_meta_monto CHECK (monto <> 0)
);
CREATE INDEX ix_aporte_meta_meta ON aporte_meta (meta_id);
