-- Fase 1 del SaaS: cada negocio ve solo sus datos. Todo lo que existe hoy (Dopamina Cocktails) queda en el
-- negocio 1; cuando se conozca el id real de Dopamina en Antigravity se reasigna con un UPDATE de negocio_id.
-- Solo se agregan columnas e índices: no se borra ni se cambia ningún dato.

ALTER TABLE producto            ADD COLUMN negocio_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE venta               ADD COLUMN negocio_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE entrada_inventario  ADD COLUMN negocio_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE passkey             ADD COLUMN negocio_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE pedido_proveedor    ADD COLUMN negocio_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE pedido_item         ADD COLUMN negocio_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE gasto               ADD COLUMN negocio_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE arqueo              ADD COLUMN negocio_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE ingreso             ADD COLUMN negocio_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE conteo_plata        ADD COLUMN negocio_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE pago_proveedor      ADD COLUMN negocio_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE traslado            ADD COLUMN negocio_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE meta_plata          ADD COLUMN negocio_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE aporte_meta         ADD COLUMN negocio_id BIGINT NOT NULL DEFAULT 1;

-- Lo que antes era único en toda la base ahora es único por negocio
ALTER TABLE producto DROP CONSTRAINT uq_producto_sabor_tipo;
ALTER TABLE producto ADD CONSTRAINT uq_producto_negocio_sabor_tipo UNIQUE (negocio_id, sabor, tipo);

-- El identificador que manda el celular (client_uid) solo debe ser único dentro de cada negocio:
-- si no, dos negocios con el mismo id (ej. importaciones con ids fijos) se perderían ventas entre sí.
ALTER TABLE venta DROP CONSTRAINT uq_venta_client_uid;
ALTER TABLE venta ADD CONSTRAINT uq_venta_negocio_client_uid UNIQUE (negocio_id, client_uid);
ALTER TABLE entrada_inventario DROP CONSTRAINT uq_entrada_client_uid;
ALTER TABLE entrada_inventario ADD CONSTRAINT uq_entrada_negocio_client_uid UNIQUE (negocio_id, client_uid);
ALTER TABLE gasto DROP CONSTRAINT uq_gasto_client_uid;
ALTER TABLE gasto ADD CONSTRAINT uq_gasto_negocio_client_uid UNIQUE (negocio_id, client_uid);
ALTER TABLE ingreso DROP CONSTRAINT uq_ingreso_client_uid;
ALTER TABLE ingreso ADD CONSTRAINT uq_ingreso_negocio_client_uid UNIQUE (negocio_id, client_uid);
ALTER TABLE conteo_plata DROP CONSTRAINT uq_conteo_plata_client_uid;
ALTER TABLE conteo_plata ADD CONSTRAINT uq_conteo_plata_negocio_client_uid UNIQUE (negocio_id, client_uid);
ALTER TABLE traslado DROP CONSTRAINT uq_traslado_client_uid;
ALTER TABLE traslado ADD CONSTRAINT uq_traslado_negocio_client_uid UNIQUE (negocio_id, client_uid);
ALTER TABLE meta_plata DROP CONSTRAINT uq_meta_plata_client_uid;
ALTER TABLE meta_plata ADD CONSTRAINT uq_meta_plata_negocio_client_uid UNIQUE (negocio_id, client_uid);
ALTER TABLE aporte_meta DROP CONSTRAINT uq_aporte_meta_client_uid;
ALTER TABLE aporte_meta ADD CONSTRAINT uq_aporte_meta_negocio_client_uid UNIQUE (negocio_id, client_uid);

DROP INDEX uq_arqueo_dia;
CREATE UNIQUE INDEX uq_arqueo_negocio_dia ON arqueo (negocio_id, dia);

-- La configuración pasa a ser por negocio: la clave sola ya no es la llave primaria
CREATE TABLE config_negocio (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    negocio_id BIGINT       NOT NULL DEFAULT 1,
    clave      VARCHAR(50)  NOT NULL,
    valor      VARCHAR(500) NOT NULL DEFAULT '',
    nota       VARCHAR(200),
    CONSTRAINT uq_config_negocio_clave UNIQUE (negocio_id, clave)
);
INSERT INTO config_negocio (negocio_id, clave, valor, nota) SELECT 1, clave, valor, nota FROM config;
DROP TABLE config;
ALTER TABLE config_negocio RENAME TO config;

-- Casi todas las consultas filtran por negocio y por fecha
CREATE INDEX ix_producto_negocio       ON producto (negocio_id);
CREATE INDEX ix_venta_negocio_fecha    ON venta (negocio_id, creada_en);
CREATE INDEX ix_gasto_negocio_fecha    ON gasto (negocio_id, creado_en);
CREATE INDEX ix_ingreso_negocio_fecha  ON ingreso (negocio_id, creado_en);
CREATE INDEX ix_entrada_negocio        ON entrada_inventario (negocio_id);
CREATE INDEX ix_pedido_negocio         ON pedido_proveedor (negocio_id);
CREATE INDEX ix_conteo_negocio_fecha   ON conteo_plata (negocio_id, creado_en);
