-- Dinero siempre en pesos enteros (BIGINT). Fechas en UTC con zona.

CREATE TABLE producto (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sabor        VARCHAR(80)  NOT NULL,
    tipo         VARCHAR(20)  NOT NULL,
    precio       BIGINT       NOT NULL,
    stock        INTEGER      NOT NULL DEFAULT 0,
    stock_minimo INTEGER      NOT NULL DEFAULT 3,
    activo       BOOLEAN      NOT NULL DEFAULT TRUE,
    orden        INTEGER      NOT NULL DEFAULT 0,
    CONSTRAINT uq_producto_sabor_tipo UNIQUE (sabor, tipo),
    CONSTRAINT ck_producto_tipo CHECK (tipo IN ('NORMAL', 'CREMOSO', 'GRANDE')),
    CONSTRAINT ck_producto_precio CHECK (precio >= 0),
    CONSTRAINT ck_producto_minimo CHECK (stock_minimo >= 0)
);

CREATE TABLE venta (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_uid      VARCHAR(64)  NOT NULL,
    producto_id     BIGINT       NOT NULL REFERENCES producto (id),
    cantidad        INTEGER      NOT NULL,
    precio_unitario BIGINT       NOT NULL,
    total           BIGINT       NOT NULL,
    metodo          VARCHAR(10)  NOT NULL,
    creada_en       TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_venta_client_uid UNIQUE (client_uid),
    CONSTRAINT ck_venta_cantidad CHECK (cantidad > 0),
    CONSTRAINT ck_venta_metodo CHECK (metodo IN ('NEQUI', 'EFECTIVO'))
);
CREATE INDEX ix_venta_creada_en ON venta (creada_en);
CREATE INDEX ix_venta_producto ON venta (producto_id);

CREATE TABLE entrada_inventario (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_uid  VARCHAR(64),
    producto_id BIGINT       NOT NULL REFERENCES producto (id),
    cantidad    INTEGER      NOT NULL,
    creada_en   TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_entrada_client_uid UNIQUE (client_uid),
    CONSTRAINT ck_entrada_cantidad CHECK (cantidad <> 0)
);
CREATE INDEX ix_entrada_producto ON entrada_inventario (producto_id);

CREATE TABLE config (
    clave VARCHAR(50)  PRIMARY KEY,
    valor VARCHAR(500) NOT NULL DEFAULT '',
    nota  VARCHAR(200)
);
