-- Llaves de Face ID (passkeys / WebAuthn). La llave privada nunca sale del iPhone: aquí solo va la pública.

CREATE TABLE passkey (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    credential_id   VARCHAR(512)  NOT NULL,
    public_key_cose VARCHAR(2048) NOT NULL,
    sign_count      BIGINT        NOT NULL DEFAULT 0,
    nombre          VARCHAR(80)   NOT NULL,
    creada_en       TIMESTAMP WITH TIME ZONE NOT NULL,
    usada_en        TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uq_passkey_credential UNIQUE (credential_id)
);
