-- Fase 2: pedido al proveedor con seguimiento (ENVIADO → RECIBIDO / CANCELADO).

CREATE TABLE pedido_proveedor (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estado          VARCHAR(10)  NOT NULL DEFAULT 'ENVIADO',
    creado_en       TIMESTAMP WITH TIME ZONE NOT NULL,
    recibido_en     TIMESTAMP WITH TIME ZONE,
    recibido_uid    VARCHAR(64),
    total_unidades  INTEGER      NOT NULL DEFAULT 0,
    CONSTRAINT ck_pedido_estado CHECK (estado IN ('ENVIADO', 'RECIBIDO', 'CANCELADO')),
    CONSTRAINT ck_pedido_total  CHECK (total_unidades >= 0)
);
CREATE INDEX ix_pedido_estado ON pedido_proveedor (estado);

CREATE TABLE pedido_item (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id         BIGINT    NOT NULL REFERENCES pedido_proveedor (id),
    producto_id       BIGINT    NOT NULL REFERENCES producto (id),
    cantidad_pedida   INTEGER   NOT NULL,
    cantidad_recibida INTEGER   NOT NULL DEFAULT 0,
    CONSTRAINT uq_pedido_item        UNIQUE (pedido_id, producto_id),
    CONSTRAINT ck_pedido_item_pedida CHECK (cantidad_pedida > 0),
    CONSTRAINT ck_pedido_item_llega  CHECK (cantidad_recibida >= 0)
);
CREATE INDEX ix_pedido_item_pedido ON pedido_item (pedido_id);

-- Los movimientos que nacen de "Llegó el pedido" quedan ligados al pedido
ALTER TABLE entrada_inventario ADD CONSTRAINT fk_entrada_pedido
    FOREIGN KEY (pedido_id) REFERENCES pedido_proveedor (id);
