-- Fase 3: ganancia real. Costo por producto, costo congelado en la venta y gastos del día.

ALTER TABLE producto ADD COLUMN costo BIGINT NOT NULL DEFAULT 0;
ALTER TABLE producto ADD CONSTRAINT ck_producto_costo CHECK (costo >= 0);

ALTER TABLE venta ADD COLUMN costo_unitario BIGINT NOT NULL DEFAULT 0;
ALTER TABLE venta ADD CONSTRAINT ck_venta_costo CHECK (costo_unitario >= 0);

-- Las ventas viejas quedan con el costo que se sabe hoy (el precio sí ya estaba congelado)
UPDATE venta
   SET costo_unitario = (SELECT p.costo FROM producto p WHERE p.id = venta.producto_id);

CREATE TABLE gasto (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_uid  VARCHAR(64)  NOT NULL,
    categoria   VARCHAR(20)  NOT NULL,
    concepto    VARCHAR(120),
    monto       BIGINT       NOT NULL,
    creado_en   TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_gasto_client_uid UNIQUE (client_uid),
    CONSTRAINT ck_gasto_categoria CHECK (categoria IN ('HIELO', 'TRANSPORTE', 'EMPAQUE', 'OTRO')),
    CONSTRAINT ck_gasto_monto CHECK (monto > 0)
);
CREATE INDEX ix_gasto_creada_en ON gasto (creado_en);
