-- Arqueo de caja: uno por día. El esperado es el efectivo que registró la app.
CREATE TABLE arqueo (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_uid  VARCHAR(64)  NOT NULL,
    dia         DATE         NOT NULL,
    esperado    BIGINT       NOT NULL,
    contado     BIGINT       NOT NULL,
    diferencia  BIGINT       NOT NULL,
    nota        VARCHAR(120),
    creado_en   TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_arqueo_contado CHECK (contado >= 0),
    CONSTRAINT ck_arqueo_esperado CHECK (esperado >= 0)
);

CREATE UNIQUE INDEX uq_arqueo_dia ON arqueo (dia);
CREATE INDEX ix_arqueo_creado_en ON arqueo (creado_en);
